name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          npm test > test-result.txt

      - name: Upload test results
        uses: actions/upload-artifact@v3.1.3
        with:
          name: test-results
          path: test-result.txt

  deploy:
    needs: test
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download test results
        uses: actions/download-artifact@v3.0.2
        with:
          name: test-results

      - name: Show test results
        run: cat test-result.txt

      - name: Install dependencies
        run: npm install

      - name: Start application
        run: npm start
